export { generateScaffold } from './scaffold';
export type { ScaffoldOptions, ScaffoldResult, ConflictResolution, FileResolutionMap } from './scaffold';
export { detectConflicts } from './conflict-detector';
export type { ConflictMap, ConflictCategory, FileConflict } from './conflict-detector';
export { createBackup } from './backup-manager';
export type { BackupManifest } from './backup-manager';
export { mergeClaudeMd, mergeClaudeMdTop, mergeSettingsJson, mergeMcpJson, mergeGitignore } from './merge-strategies';
export { emitEvent, readMonitorState, getAgentSummary } from './monitor';
export type { MonitorState, MonitorEvent, MonitorSummary, DynamicAgent } from './monitor';
export { detectDocker, readSandboxConfig, readSandboxPolicy, buildSandboxEnv, runInProcessSandbox, runInDockerSandbox, runInSandbox } from './sandbox';
export type { SandboxMode, SandboxConfig, SandboxPolicy, SandboxRunResult } from './sandbox';
export { detectDevServer, startDevServer, getVibeModeConfig } from './preview-server';
export type { DevServerConfig } from './preview-server';
export { detectDesignTokens, generateDefaultTokens, detectComponentRegistry, runBrandGuardian, generateDesignSystemConfig } from './design-system';
export type { DesignTokens, ComponentEntry, ComponentRegistry, BrandGuardianIssue, BrandGuardianReport } from './design-system';
