// packages/core/src/generators/merge-strategies.ts

const FISHI_START = '<!-- FISHI:START — Auto-generated by FISHI. Do not edit between markers. -->';
const FISHI_END = '<!-- FISHI:END -->';

export function mergeClaudeMd(existing: string, fishiContent: string): string {
  const section = `\n---\n### FISHI Framework\n${FISHI_START}\n${fishiContent}\n${FISHI_END}`;

  const startIdx = existing.indexOf(FISHI_START);
  const endIdx = existing.indexOf(FISHI_END);

  if (startIdx !== -1 && endIdx !== -1) {
    let sectionStart = existing.lastIndexOf('\n---\n### FISHI Framework', startIdx);
    if (sectionStart === -1) sectionStart = startIdx;
    const sectionEnd = endIdx + FISHI_END.length;
    return existing.slice(0, sectionStart) + section + existing.slice(sectionEnd);
  }

  return existing + section;
}

interface HookEntry {
  matcher: string;
  command: string;
  [key: string]: unknown;
}

interface SettingsJson {
  hooks?: Record<string, HookEntry[]>;
  permissions?: { allow?: string[]; deny?: string[] };
  env?: Record<string, string>;
  enabledPlugins?: string[];
  [key: string]: unknown;
}

export function mergeSettingsJson(existing: SettingsJson, fishi: SettingsJson): SettingsJson {
  const result: SettingsJson = { ...existing };

  const mergedHooks: Record<string, HookEntry[]> = { ...existing.hooks };
  if (fishi.hooks) {
    for (const [event, entries] of Object.entries(fishi.hooks)) {
      if (!mergedHooks[event]) {
        mergedHooks[event] = [...entries];
      } else {
        for (const entry of entries) {
          const isDuplicate = mergedHooks[event].some(
            (e) => e.matcher === entry.matcher && e.command === entry.command
          );
          if (!isDuplicate) {
            mergedHooks[event] = [...mergedHooks[event], entry];
          }
        }
      }
    }
  }
  result.hooks = mergedHooks;

  const existingAllow = existing.permissions?.allow || [];
  const fishiAllow = fishi.permissions?.allow || [];
  const existingDeny = existing.permissions?.deny || [];
  const fishiDeny = fishi.permissions?.deny || [];

  result.permissions = {
    allow: [...new Set([...existingAllow, ...fishiAllow])],
    deny: [...new Set([...existingDeny, ...fishiDeny])],
  };

  if (fishi.env) {
    result.env = { ...fishi.env, ...existing.env };
  }

  if (fishi.enabledPlugins) {
    result.enabledPlugins = [
      ...new Set([...(existing.enabledPlugins || []), ...fishi.enabledPlugins]),
    ];
  }

  return result;
}

interface McpJson {
  mcpServers: Record<string, Record<string, unknown>>;
  [key: string]: unknown;
}

export function mergeMcpJson(existing: McpJson, fishi: McpJson): McpJson {
  const merged = { ...existing, mcpServers: { ...existing.mcpServers } };
  for (const [name, config] of Object.entries(fishi.mcpServers)) {
    if (!(name in merged.mcpServers)) {
      merged.mcpServers[name] = config;
    }
  }
  return merged;
}

export function mergeGitignore(existing: string, fishiAdditions: string): string {
  if (existing.includes('.trees/')) {
    return existing;
  }
  return existing + fishiAdditions;
}
