import type { CostMode, ProjectType } from '../../types';

export interface FishiYamlOptions {
  projectName: string;
  projectDescription: string;
  projectType: ProjectType;
  costMode: CostMode;
  language?: string;
  framework?: string;
}

export function getFishiYamlTemplate(options: FishiYamlOptions): string {
  const {
    projectName,
    projectDescription,
    projectType,
    costMode,
    language,
    framework,
  } = options;

  const opusTasks =
    costMode === 'economy'
      ? '[]'
      : `
    - architecture_review
    - complex_debugging
    - security_audit
    - cross_domain_planning`;

  const sonnetTasks = `
    - feature_implementation
    - code_review
    - test_writing
    - refactoring
    - sprint_planning`;

  const haikuTasks =
    costMode === 'performance'
      ? '[]'
      : `
    - status_checks
    - file_search
    - simple_edits
    - documentation`;

  return `# FISHI Configuration
# Generated by fishi init
version: "1.0"

project:
  name: "${projectName}"
  description: "${projectDescription}"
  type: ${projectType}
${language ? `  language: "${language}"\n` : ''}${framework ? `  framework: "${framework}"\n` : ''}
execution:
  mode: cli
  parallel: true
  max_parallel: 4

cost_mode: ${costMode}

model_routing:
  opus:${opusTasks}
  sonnet:${sonnetTasks}
  haiku:${haikuTasks}

git:
  strategy: worktree-per-agent
  main_branch: main
  dev_branch: dev
  worktree_dir: .trees
  auto_commit: true
  commit_prefix: true

gates:
  enabled: true
  gate_points:
    - prd_approval
    - architecture_approval
    - sprint_plan_approval
    - pre_merge_review

taskboard:
  enabled: true
  auto_update: true
  sprint_duration: auto

state:
  checkpoint_on_stop: true
  max_checkpoints: 50
  compress_after_sprint: true

dynamic_agents:
  enabled: true
  require_approval: ${projectType === 'brownfield' ? 'true' : 'false'}

mcp:
  auto_discover: true
  core:
    - github
    - sequential-thinking
    - context7
  project: []
  agent_access:
    master-orchestrator:
      - github
      - sequential-thinking
    planning-lead:
      - sequential-thinking
      - context7
    dev-lead:
      - github
      - context7
    qa-lead:
      - github
    devops-lead:
      - github

plugins: []
`;
}
