// Re-export core types for convenience
export type {
  FishiConfig,
  ProjectConfig,
  ExecutionConfig,
  ModelRoutingConfig,
  GitConfig,
  GateConfig,
  TaskboardConfig,
  StateConfig,
  DynamicAgentConfig,
  McpConfig,
  McpServerConfig,
  AgentDefinition,
  DetectionResult,
  DetectionCheck,
  InitOptions,
  ProjectType,
  CostMode,
  ModelTier,
  TaskStatus,
  GateStatus,
  AgentRole,
} from '@qlucent/fishi-core';
