// packages/core/src/__tests__/merge-strategies.test.ts
import { describe, it, expect } from 'vitest';
import {
  mergeClaudeMd,
  mergeSettingsJson,
  mergeMcpJson,
  mergeGitignore,
} from '../generators/merge-strategies';

describe('mergeClaudeMd', () => {
  it('appends FISHI section to existing content', () => {
    const existing = '# My Project\n\nExisting instructions here.';
    const fishiContent = 'FISHI orchestration rules...';
    const result = mergeClaudeMd(existing, fishiContent);

    expect(result).toContain('# My Project');
    expect(result).toContain('Existing instructions here.');
    expect(result).toContain('### FISHI Framework');
    expect(result).toContain('<!-- FISHI:START — Auto-generated by FISHI.');
    expect(result).toContain('<!-- FISHI:END -->');
    expect(result).toContain('FISHI orchestration rules...');
  });

  it('is idempotent — replaces existing FISHI section on re-merge', () => {
    const existing = '# My Project\n\n---\n### FISHI Framework\n<!-- FISHI:START — Auto-generated by FISHI. Do not edit between markers. -->\nold content\n<!-- FISHI:END -->';
    const fishiContent = 'new content';
    const result = mergeClaudeMd(existing, fishiContent);

    expect(result).not.toContain('old content');
    expect(result).toContain('new content');
    expect(result.match(/FISHI:START/g)).toHaveLength(1);
  });

  it('preserves all content above FISHI section', () => {
    const existing = '# Project\n\n## Section A\nImportant stuff\n\n## Section B\nMore stuff';
    const fishiContent = 'fishi rules';
    const result = mergeClaudeMd(existing, fishiContent);

    expect(result).toContain('## Section A\nImportant stuff');
    expect(result).toContain('## Section B\nMore stuff');
  });

  it('preserves content after FISHI:END on re-merge', () => {
    const existing = '# Project\n\n---\n### FISHI Framework\n<!-- FISHI:START — Auto-generated by FISHI. Do not edit between markers. -->\nold\n<!-- FISHI:END -->\n\n## My Footer\nKeep this.';
    const fishiContent = 'updated';
    const result = mergeClaudeMd(existing, fishiContent);

    expect(result).toContain('## My Footer');
    expect(result).toContain('Keep this.');
    expect(result).toContain('updated');
    expect(result).not.toContain('old');
  });
});

describe('mergeSettingsJson', () => {
  it('adds FISHI hooks alongside existing hooks', () => {
    const existing = {
      hooks: {
        PostToolUse: [{ matcher: 'Write|Edit', command: 'prettier --write $FILE' }],
      },
      permissions: { allow: ['Read'], deny: [] },
    };
    const fishi = {
      hooks: {
        SessionStart: [{ matcher: '', command: 'node .fishi/scripts/session-start.mjs' }],
        PostToolUse: [{ matcher: 'Write|Edit', command: 'node .fishi/scripts/post-edit.mjs' }],
      },
      permissions: { allow: ['Read', 'Write', 'Glob'], deny: ['Bash(rm -rf *)'] },
    };
    const result = mergeSettingsJson(existing, fishi);

    expect(result.hooks.PostToolUse).toContainEqual({
      matcher: 'Write|Edit', command: 'prettier --write $FILE',
    });
    expect(result.hooks.PostToolUse).toContainEqual({
      matcher: 'Write|Edit', command: 'node .fishi/scripts/post-edit.mjs',
    });
    expect(result.hooks.SessionStart).toHaveLength(1);
    expect(result.permissions.allow).toContain('Read');
    expect(result.permissions.allow).toContain('Write');
    expect(result.permissions.allow).toContain('Glob');
    expect(result.permissions.allow.filter((p: string) => p === 'Read')).toHaveLength(1);
    expect(result.permissions.deny).toContain('Bash(rm -rf *)');
  });

  it('preserves existing env and other keys', () => {
    const existing = {
      hooks: {},
      permissions: { allow: [], deny: [] },
      env: { API_KEY: 'secret' },
      enabledPlugins: ['my-plugin'],
      customKey: 'preserved',
    };
    const fishi = {
      hooks: {},
      permissions: { allow: [], deny: [] },
      env: { FISHI_MODE: 'auto' },
      enabledPlugins: ['fishi-plugin'],
    };
    const result = mergeSettingsJson(existing, fishi);

    expect(result.env.API_KEY).toBe('secret');
    expect(result.env.FISHI_MODE).toBe('auto');
    expect(result.enabledPlugins).toContain('my-plugin');
    expect(result.enabledPlugins).toContain('fishi-plugin');
    expect(result.customKey).toBe('preserved');
  });

  it('deduplicates hooks by (eventName, matcher, command) triple', () => {
    const existing = {
      hooks: {
        PreToolUse: [{ matcher: 'Bash', command: 'node safety.mjs' }],
      },
      permissions: { allow: [], deny: [] },
    };
    const fishi = {
      hooks: {
        PreToolUse: [{ matcher: 'Bash', command: 'node safety.mjs' }],
      },
      permissions: { allow: [], deny: [] },
    };
    const result = mergeSettingsJson(existing, fishi);
    expect(result.hooks.PreToolUse).toHaveLength(1);
  });
});

describe('mergeMcpJson', () => {
  it('adds new MCP servers without removing existing', () => {
    const existing = {
      mcpServers: {
        'astro-docs': { type: 'stdio', command: 'npx', args: ['astro-docs'] },
      },
    };
    const fishi = {
      mcpServers: {
        github: { type: 'http', url: 'https://api.githubcopilot.com/mcp/' },
        'sequential-thinking': { type: 'stdio', command: 'npx', args: ['-y', '@anthropic/sequential-thinking-mcp'] },
      },
    };
    const result = mergeMcpJson(existing, fishi);

    expect(result.mcpServers['astro-docs']).toBeDefined();
    expect(result.mcpServers['github']).toBeDefined();
    expect(result.mcpServers['sequential-thinking']).toBeDefined();
  });

  it('does not overwrite existing server with same name', () => {
    const existing = {
      mcpServers: {
        github: { type: 'stdio', command: 'custom-gh' },
      },
    };
    const fishi = {
      mcpServers: {
        github: { type: 'http', url: 'https://api.githubcopilot.com/mcp/' },
      },
    };
    const result = mergeMcpJson(existing, fishi);
    expect(result.mcpServers.github.command).toBe('custom-gh');
  });
});

describe('mergeGitignore', () => {
  it('appends FISHI entries to existing gitignore', () => {
    const existing = 'node_modules/\ndist/\n';
    const fishiAdditions = '\n# FISHI framework\n.trees/\n.fishi/logs/\n';
    const result = mergeGitignore(existing, fishiAdditions);

    expect(result).toContain('node_modules/');
    expect(result).toContain('.trees/');
  });

  it('is idempotent — does not append if .trees/ already present', () => {
    const existing = 'node_modules/\n.trees/\n';
    const fishiAdditions = '\n# FISHI framework\n.trees/\n.fishi/logs/\n';
    const result = mergeGitignore(existing, fishiAdditions);

    expect(result).toBe(existing);
  });
});
