import type { BrownfieldAnalysis } from './brownfield.js';

export function generateBrownfieldReport(analysis: BrownfieldAnalysis): string {
  const sections: string[] = [];

  // Header
  sections.push(`# Brownfield Analysis Report

> Auto-generated by FISHI brownfield analyzer.
> This report captures the state of the codebase at initialization time.

---`);

  // Architecture Overview
  sections.push(buildArchitectureSection(analysis));

  // Tech Stack Inventory
  sections.push(buildTechStackSection(analysis));

  // Tooling Inventory
  sections.push(buildToolingSection(analysis));

  // Code Statistics
  sections.push(buildStatsSection(analysis));

  // Conventions Discovered
  sections.push(buildConventionsSection(analysis));

  // Tech Debt Signals
  sections.push(buildTechDebtSection(analysis));

  // Recommendations
  sections.push(buildRecommendationsSection(analysis));

  return sections.join('\n\n');
}

function buildArchitectureSection(analysis: BrownfieldAnalysis): string {
  let section = `## Architecture Overview\n`;

  if (analysis.monorepo) {
    section += `\n**Monorepo**: Yes\n`;
  }

  if (analysis.codePatterns.length > 0) {
    section += `\n### Detected Patterns\n\n`;
    for (const pattern of analysis.codePatterns) {
      const confidenceLabel = pattern.confidence >= 80 ? 'high' : pattern.confidence >= 60 ? 'medium' : 'low';
      section += `- **${pattern.name}** (${confidenceLabel} confidence) — ${pattern.evidence}\n`;
    }
  } else {
    section += `\nNo strong architectural patterns detected.\n`;
  }

  if (analysis.structure) {
    section += `\n### Directory Structure\n\n\`\`\`\n${analysis.structure}\`\`\`\n`;
  }

  return section;
}

function buildTechStackSection(analysis: BrownfieldAnalysis): string {
  const rows: Array<[string, string]> = [
    ['Language', analysis.language || 'Unknown'],
    ['Framework', analysis.framework || 'None detected'],
    ['ORM', analysis.orm || 'None detected'],
    ['Database', analysis.database || 'None detected'],
    ['Auth Provider', analysis.authProvider || 'None detected'],
    ['CSS Framework', analysis.cssFramework || 'None detected'],
    ['API Style', analysis.apiStyle || 'None detected'],
  ];

  let section = `## Tech Stack Inventory\n\n`;
  section += `| Category | Value |\n|----------|-------|\n`;
  for (const [cat, val] of rows) {
    section += `| ${cat} | ${val} |\n`;
  }

  return section;
}

function buildToolingSection(analysis: BrownfieldAnalysis): string {
  const rows: Array<[string, string]> = [
    ['Package Manager', analysis.packageManager || 'Unknown'],
    ['Linter', analysis.linter || 'None detected'],
    ['Formatter', analysis.formatter || 'None detected'],
    ['Test Framework', analysis.testFramework || 'None detected'],
    ['Has Tests', analysis.hasTests ? 'Yes' : 'No'],
    ['Has CI/CD', analysis.hasCiCd ? 'Yes' : 'No'],
  ];

  let section = `## Tooling Inventory\n\n`;
  section += `| Tool | Value |\n|------|-------|\n`;
  for (const [tool, val] of rows) {
    section += `| ${tool} | ${val} |\n`;
  }

  return section;
}

function buildStatsSection(analysis: BrownfieldAnalysis): string {
  const { fileStats } = analysis;

  let section = `## Code Statistics\n\n`;
  section += `| Metric | Count |\n|--------|-------|\n`;
  section += `| Total Files | ${fileStats.totalFiles} |\n`;
  section += `| Code Files | ${fileStats.codeFiles} |\n`;
  section += `| Test Files | ${fileStats.testFiles} |\n`;
  section += `| Config Files | ${fileStats.configFiles} |\n`;
  section += `| Doc Files | ${fileStats.docFiles} |\n`;
  section += `| Dependencies | ${analysis.dependencyCount} |\n`;

  if (fileStats.largestFiles.length > 0) {
    section += `\n### Largest Code Files\n\n`;
    section += `| File | Lines |\n|------|-------|\n`;
    for (const file of fileStats.largestFiles) {
      section += `| \`${file.path}\` | ${file.lines} |\n`;
    }
  }

  return section;
}

function buildConventionsSection(analysis: BrownfieldAnalysis): string {
  let section = `## Conventions Discovered\n\n`;

  if (analysis.conventions.length > 0) {
    for (const conv of analysis.conventions) {
      section += `- ${conv}\n`;
    }
  } else {
    section += `_No specific conventions detected._\n`;
  }

  return section;
}

function buildTechDebtSection(analysis: BrownfieldAnalysis): string {
  let section = `## Tech Debt Signals\n\n`;

  if (analysis.techDebt.length > 0) {
    for (const debt of analysis.techDebt) {
      section += `- ${debt}\n`;
    }
  } else {
    section += `_No significant tech debt signals detected._\n`;
  }

  return section;
}

function buildRecommendationsSection(analysis: BrownfieldAnalysis): string {
  const recs: string[] = [];

  // Recommendations based on analysis
  if (!analysis.hasTests) {
    recs.push('Add a test framework and establish a testing baseline before making changes.');
  }
  if (!analysis.hasCiCd) {
    recs.push('Set up CI/CD to validate changes automatically.');
  }
  if (!analysis.linter) {
    recs.push('Add a linter (ESLint or Biome recommended) to enforce code consistency.');
  }
  if (!analysis.formatter) {
    recs.push('Add a formatter (Prettier or Biome recommended) to maintain consistent style.');
  }
  if (analysis.techDebt.length > 0) {
    recs.push('Address tech debt items before adding new features — see Tech Debt section above.');
  }
  if (analysis.existingAgents.length > 0) {
    recs.push(`Existing agent definitions found (${analysis.existingAgents.length}). Review for compatibility with FISHI agents.`);
  }
  if (analysis.fileStats.largestFiles.some(f => f.lines > 500)) {
    recs.push('Some large files detected. Consider refactoring files over 500 lines into smaller modules.');
  }
  if (analysis.dependencyCount > 80) {
    recs.push('High dependency count. Audit unused dependencies with `depcheck` or similar tools.');
  }
  if (analysis.codePatterns.length > 0) {
    recs.push('Respect discovered code patterns when adding new features. See Architecture section.');
  }

  let section = `## Recommendations for FISHI Integration\n\n`;
  if (recs.length > 0) {
    for (const rec of recs) {
      section += `- ${rec}\n`;
    }
  } else {
    section += `Codebase is in good shape. Proceed with normal FISHI workflow.\n`;
  }

  return section;
}
